name: Deploy Spring Boot App to Azure

on:
  push:
    branches:
      - main

env:
  JAVA_VERSION: 17
  AZURE_SUBSCRIPTION: eb78b1af-ed9c-48ff-8876-77b63dccc3b9

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build the Spring Boot App
        run: mvn clean package -DskipTests

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Spring Apps
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: eb78b1af-ed9c-48ff-8876-77b63dccc3b9
          service-name: book-list-app
          app-name: bookservice
          package: target/*.jar
