
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 21
  AZURE_SUBSCRIPTION: eb78b1af-ed9c-48ff-8876-77b63dccc3b9

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy to production with artifact
        uses: azure/spring-cloud-deploy@v1
        with:
          azure-subscription: eb78b1af-ed9c-48ff-8876-77b63dccc3b9
          action: Deploy
          service-name: spring-blog
          app-name: spring-blog
          use-staging-deployment: false
          package: '*.jar'